#!/usr/bin/env python3

import sys

def factorize(n):
    factors = []
    for i in range(2, int(n**0.5) + 1):
        while n % i == 0:
            factors.append(i)
            n //= i
    if n > 1:
        factors.append(n)
    return factors

def main():
    if len(sys.argv) != 2:
        print("Usage: {} <file>".format(sys.argv[0]))
        sys.exit(1)

    input_file = sys.argv[1]
    with open(input_file, 'r') as file:
        numbers = file.readlines()

    for number in numbers:
        n = int(number.strip())
        factors = factorize(n)
        print("{}={}".format(n, '*'.join(map(str, factors))))

if __name__ == "__main__":
    main()

